spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/griefgrocer?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
logging:
  pattern:
    console: "%boldGreen(%d{yyyy-MM-dd HH:mm:ss.SSS}) %highlight(%-5level) %cyan(%-35logger{35}) - %msg %n"
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hiramgames.domain